### PR TITLE
Bugfixes

### PR DESCRIPTION
**Pull request by marble-sh**

### CODE REVIEW

**Comment by marble-sh** [comment]
Fixes travis failures from: https://github.com/matryer/bitbar-plugins/pull/823

**Comment by mustafaturksavas** [comment]
Hi @marblenix. I have a question about jq, since I don't have it installed, I will just need to install it to be able to use this plugin. And this question comes from pure ignorance, is it still the best way to go to solve this problem? Or, would this still work ok, without using jq and jq just makes it better?

**Comment by marble-sh** [comment]
You can install jq with `brew install jq` if you have homebrew installed.

With the changes in this pull request jq becomes a requirement to use the plugin.

**Comment by mustafaturksavas** [comment]
I guess I wasn't clear. My issue wasn't that I didn't know how to install jq, I meant even if I didn't have jq installed being the "developer" of the plugin, how can I expect people installing plugin to have that. Having a dependency for a tool as simple as this one seems too much to me, but like I said, I have very limited info about the topic. So what I'm asking is, is it too terrible to just go with the way I wrote it, with no jq? I can see that it's not the best way, but if it's not a terrible one, wouldn't it make sense to keep it without dependencies?

**Comment by marble-sh** [comment]
It is your plugin after all. I don't see dependencies as that much of a problem, and other plugins require jq as well:

https://getbitbar.com/plugins/Dev/MachineBox/machinebox.1m.sh
https://getbitbar.com/plugins/Dev/Bamboo/bamboo_build_status.1m.sh


If dependencies are really a problem though, you can re-write the plugin in ruby or python, both of which have builtin methods to deal with JSON.

And if you insist on bash + unix tools see this stackoverflow answer for a more robust way of parsing json: https://stackoverflow.com/a/6852427

edit:

Alternatively you could also put something like this in the script to help the user install jq:

```
command -v jq >/dev/null 2>&1 || { echo >&2 "Click to install jq command... | href=https://stedolan.github.io/jq/?source=bitbar"; exit 0; }
```

I got the above from: https://raw.githubusercontent.com/matryer/bitbar-plugins/master/Dev/MachineBox/machinebox.1m.sh

**Comment by mustafaturksavas** [comment]
Hi @marblenix I came up with this:

```
bit_price=$(curl -s "https://api.coinbase.com/v2/prices/BTC-USD/buy" -H "CB-VERSION: 2015-04-08" | python -c "import sys, json; print json.load(sys.stdin)['data']['amount']")
```

If this look good to you, can you edit your code and create another pull request? Since you solved the issue, I don't feel comfortable closing your pull request and make it look like I fixed it.

**Comment by marble-sh** [comment]
Sounds good, I've changed it to python. Let me know if it works for you.

**Pull request merged**
